CREATE TABLE "characters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"class" varchar(100) DEFAULT '',
	"level" integer DEFAULT 1 NOT NULL,
	"species" varchar(100) DEFAULT '',
	"subclass" varchar(100) DEFAULT '',
	"background" varchar(100) DEFAULT '',
	"xp" integer DEFAULT 0 NOT NULL,
	"abilities" jsonb NOT NULL,
	"skills" jsonb NOT NULL,
	"armor_class" integer DEFAULT 10 NOT NULL,
	"hit_points" jsonb NOT NULL,
	"hit_dice" jsonb NOT NULL,
	"death_saves" jsonb NOT NULL,
	"speed" integer DEFAULT 30 NOT NULL,
	"size" varchar(50) DEFAULT 'Médio',
	"heroic_inspiration" boolean DEFAULT false,
	"weapons" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"spells" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"spell_slots" jsonb NOT NULL,
	"spellcasting_ability" varchar(50) DEFAULT '',
	"inventory" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"attuned_items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"coins" jsonb NOT NULL,
	"class_features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"species_traits" varchar(2000) DEFAULT '',
	"feats" varchar(2000) DEFAULT '',
	"armor_training" varchar(255) DEFAULT '',
	"weapon_training" varchar(255) DEFAULT '',
	"tool_training" varchar(255) DEFAULT '',
	"personality_and_history" varchar(5000) DEFAULT '',
	"alignment" varchar(100) DEFAULT '',
	"languages" varchar(500) DEFAULT '',
	"campaign_notes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"custom_fields" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"bonuses" jsonb DEFAULT '{"proficiencyBonus":0,"initiative":0,"savingThrows":{},"skills":{}}'::jsonb NOT NULL,
	"user_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
