import {NewCharacterRecord} from '../../database/schema';

export function buildDefaultCharacter(name: string): NewCharacterRecord {
    const now = new Date();
    return {
        name,
        class: '',
        level: 1,
        background: '',
        species: '',
        subclass: '',
        xp: 0,
        abilities: {
            strength: {value: 10, proficient: false},
            dexterity: {value: 10, proficient: false},
            constitution: {value: 10, proficient: false},
            intelligence: {value: 10, proficient: false},
            wisdom: {value: 10, proficient: false},
            charisma: {value: 10, proficient: false},
        },
        skills: [
            {name: 'Acrobacia', ability: 'dexterity', proficient: false, expertise: false},
            {name: 'Arcanismo', ability: 'intelligence', proficient: false, expertise: false},
            {name: 'Atletismo', ability: 'strength', proficient: false, expertise: false},
            {name: 'Atuação', ability: 'charisma', proficient: false, expertise: false},
            {name: 'Enganação', ability: 'charisma', proficient: false, expertise: false},
            {name: 'Furtividade', ability: 'dexterity', proficient: false, expertise: false},
            {name: 'História', ability: 'intelligence', proficient: false, expertise: false},
            {name: 'Intimidação', ability: 'charisma', proficient: false, expertise: false},
            {name: 'Intuição', ability: 'wisdom', proficient: false, expertise: false},
            {name: 'Investigação', ability: 'intelligence', proficient: false, expertise: false},
            {name: 'Lidar com Animais', ability: 'wisdom', proficient: false, expertise: false},
            {name: 'Medicina', ability: 'wisdom', proficient: false, expertise: false},
            {name: 'Natureza', ability: 'intelligence', proficient: false, expertise: false},
            {name: 'Percepção', ability: 'wisdom', proficient: false, expertise: false},
            {name: 'Persuasão', ability: 'charisma', proficient: false, expertise: false},
            {name: 'Prestidigitação', ability: 'dexterity', proficient: false, expertise: false},
            {name: 'Religião', ability: 'intelligence', proficient: false, expertise: false},
            {name: 'Sobrevivência', ability: 'wisdom', proficient: false, expertise: false},
        ],
        armorClass: 10,
        hitPoints: {current: 10, max: 10, temp: 0},
        hitDice: {total: '1d10', used: 0},
        deathSaves: {successes: 0, failures: 0},
        speed: 30,
        size: 'Médio',
        heroicInspiration: false,
        weapons: [],
        spells: [],
        spellSlots: {
            1: {total: 0, used: 0},
            2: {total: 0, used: 0},
            3: {total: 0, used: 0},
            4: {total: 0, used: 0},
            5: {total: 0, used: 0},
            6: {total: 0, used: 0},
            7: {total: 0, used: 0},
            8: {total: 0, used: 0},
            9: {total: 0, used: 0},
        },
        spellcastingAbility: '',
        inventory: [],
        attunedItems: [],
        coins: {cp: 0, sp: 0, ep: 0, gp: 0, pp: 0},
        classFeatures: [],
        speciesTraits: '',
        feats: '',
        armorTraining: '',
        weaponTraining: '',
        toolTraining: '',
        personalityAndHistory: '',
        alignment: '',
        languages: '',
        campaignNotes: [],
        customFields: [],
        bonuses: {
            proficiencyBonus: 0,
            initiative: 0,
            savingThrows: {},
            skills: {},
        },
        createdAt: now,
        updatedAt: now,
    };
}